//! Human-readable analysis reports (plain text and Markdown).

use super::findings::Severity;
use super::Analysis;
use crate::shellbags::ScanResult;
use crate::util::Timestamp;
use std::fmt::Write;

fn ts(t: Option<Timestamp>) -> String {
    t.map(|t| t.to_short()).unwrap_or_else(|| "-".into())
}

fn md_escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('|', "\\|")
        .replace('*', "\\*")
        .replace('_', "\\_")
        .replace('<', "&lt;")
}

pub const INTERPRETATION: &str = "\
Timestamp semantics used by greybags:
- last_interacted: LastWrite of the PARENT BagMRU key when the folder is at MRU position 0, i.e. the last time this folder was opened/selected.
- first_interacted: LastWrite of the folder's OWN BagMRU key when it has no registered children, i.e. (approximately) when the folder was first opened.
- last_explored: LastWrite of the folder's own key when it has children, i.e. the last time a sub-folder was registered while browsing it.
- target created/modified/accessed: the folder's own MAC times as captured in the shell item when it was registered (FAT values have 2-second precision). They describe the folder, not the user.
All times are UTC.";

pub fn markdown(analysis: &Analysis, scan: &ScanResult) -> String {
    let mut s = String::new();
    let sm = &analysis.summary;
    let _ = writeln!(s, "# ShellBags analysis report\n");
    let _ = writeln!(
        s,
        "_Generated by {}. All times UTC._\n",
        analysis.generated_by
    );
    let _ = writeln!(s, "## Evidence\n");
    let _ = writeln!(
        s,
        "| Hive | Type | User | Dirty | Logs applied | Entries | Recovered |"
    );
    let _ = writeln!(s, "|---|---|---|---|---|---|---|");
    for h in &scan.hives {
        let applied = h
            .recovery
            .as_ref()
            .map(|r| r.entries_applied.to_string())
            .unwrap_or_else(|| "-".into());
        let _ = writeln!(
            s,
            "| {} | {} | {} | {} | {} | {} | {} |",
            md_escape(&h.path),
            h.kind.label(),
            md_escape(h.user.as_deref().unwrap_or("?")),
            if h.dirty { "yes" } else { "no" },
            applied,
            h.entries,
            h.recovered
        );
    }
    let warnings: Vec<String> = scan
        .hives
        .iter()
        .flat_map(|h| h.warnings.iter().map(move |w| format!("{}: {w}", h.path)))
        .chain(scan.errors.iter().cloned())
        .collect();
    if !warnings.is_empty() {
        let _ = writeln!(
            s,
            "\n<details><summary>Parser warnings ({})</summary>\n",
            warnings.len()
        );
        for w in warnings.iter().take(200) {
            let _ = writeln!(s, "- {}", md_escape(w));
        }
        let _ = writeln!(s, "\n</details>");
    }

    let _ = writeln!(s, "\n## Summary\n");
    let _ = writeln!(
        s,
        "- Users: {}",
        if sm.users.is_empty() {
            "unknown".into()
        } else {
            sm.users.join(", ")
        }
    );
    let _ = writeln!(
        s,
        "- Entries: {} ({} active, {} orphaned, {} recovered)",
        sm.entries, sm.active, sm.orphaned, sm.recovered
    );
    let _ = writeln!(
        s,
        "- Activity window: {} → {}",
        ts(sm.earliest_activity),
        ts(sm.latest_activity)
    );
    let _ = writeln!(s, "\n| Shell item type | Count |\n|---|---|");
    for (t, n) in &sm.by_type {
        let _ = writeln!(s, "| {t} | {n} |");
    }
    if !sm.volumes.is_empty() {
        let _ = writeln!(
            s,
            "\n| Volume / share | Entries | First activity | Last activity |\n|---|---|---|---|"
        );
        for v in &sm.volumes {
            let _ = writeln!(
                s,
                "| {} | {} | {} | {} |",
                md_escape(&v.volume),
                v.entries,
                ts(v.first_activity),
                ts(v.last_activity)
            );
        }
    }

    let _ = writeln!(s, "\n## Findings\n");
    if analysis.findings.is_empty() {
        let _ = writeln!(s, "No findings.");
    }
    for sev in [
        Severity::High,
        Severity::Medium,
        Severity::Low,
        Severity::Info,
    ] {
        let list: Vec<_> = analysis
            .findings
            .iter()
            .filter(|f| f.severity == sev)
            .collect();
        if list.is_empty() {
            continue;
        }
        let _ = writeln!(s, "### {} ({})\n", sev.label(), list.len());
        for f in list {
            let _ = writeln!(s, "#### {}\n", md_escape(&f.title));
            let _ = writeln!(s, "- Rule: `{}`", f.rule);
            if let Some(u) = &f.user {
                let _ = writeln!(s, "- User: {}", md_escape(u));
            }
            if f.first_seen.is_some() {
                let _ = writeln!(s, "- Activity: {} → {}", ts(f.first_seen), ts(f.last_seen));
            }
            let _ = writeln!(s, "- Why it matters: {}", f.rationale);
            if !f.paths.is_empty() {
                let _ = writeln!(s, "- Paths:");
                for p in &f.paths {
                    let _ = writeln!(s, "  - `{}`", p.replace('`', "'"));
                }
            }
            let _ = writeln!(s);
        }
    }

    let _ = writeln!(s, "## Most recent folder activity\n");
    let _ = writeln!(s, "| Time (UTC) | User | Path |\n|---|---|---|");
    for r in &sm.most_recent {
        let _ = writeln!(
            s,
            "| {} | {} | {} |",
            r.timestamp.to_short(),
            md_escape(r.user.as_deref().unwrap_or("?")),
            md_escape(&r.path)
        );
    }
    let _ = writeln!(s, "\n## Interpretation notes\n");
    for line in INTERPRETATION.lines() {
        let _ = writeln!(s, "{line}");
    }
    s
}

pub fn text(analysis: &Analysis, scan: &ScanResult) -> String {
    let mut s = String::new();
    let sm = &analysis.summary;
    let rule = "=".repeat(78);
    let _ = writeln!(
        s,
        "{rule}\n ShellBags analysis — {}\n{rule}",
        analysis.generated_by
    );
    for h in &scan.hives {
        let logs = match &h.recovery {
            Some(r) if r.entries_applied > 0 => {
                format!(", logs applied ({} entries)", r.entries_applied)
            }
            _ if h.dirty => ", DIRTY (no logs applied)".to_string(),
            _ => String::new(),
        };
        let _ = writeln!(
            s,
            " Hive: {} [{}{}] user={} entries={} recovered={}",
            h.path,
            h.kind.label(),
            logs,
            h.user.as_deref().unwrap_or("?"),
            h.entries,
            h.recovered
        );
    }
    for e in &scan.errors {
        let _ = writeln!(s, " ERROR: {e}");
    }
    let _ = writeln!(
        s,
        "\n Entries: {} ({} active, {} orphaned, {} recovered)",
        sm.entries, sm.active, sm.orphaned, sm.recovered
    );
    let _ = writeln!(
        s,
        " Activity window (UTC): {} -> {}",
        ts(sm.earliest_activity),
        ts(sm.latest_activity)
    );
    let types: Vec<String> = sm
        .by_type
        .iter()
        .map(|(t, n)| format!("{t}: {n}"))
        .collect();
    let _ = writeln!(s, " Types: {}", types.join(", "));
    if !sm.volumes.is_empty() {
        let _ = writeln!(s, "\n Volumes / shares:");
        for v in &sm.volumes {
            let _ = writeln!(
                s,
                "   {:<32} {:>5} entries  {} -> {}",
                v.volume,
                v.entries,
                ts(v.first_activity),
                ts(v.last_activity)
            );
        }
    }
    let _ = writeln!(
        s,
        "\n FINDINGS ({})\n {}",
        analysis.findings.len(),
        "-".repeat(76)
    );
    for f in &analysis.findings {
        let _ = writeln!(s, " [{:<6}] {}", f.severity.label(), f.title);
        if f.first_seen.is_some() {
            let _ = writeln!(
                s,
                "          when: {} -> {}{}",
                ts(f.first_seen),
                ts(f.last_seen),
                f.user
                    .as_ref()
                    .map(|u| format!("  user: {u}"))
                    .unwrap_or_default()
            );
        }
        for p in f.paths.iter().take(6) {
            let _ = writeln!(s, "          - {p}");
        }
        if f.paths.len() > 6 {
            let _ = writeln!(s, "          - ... ({} more)", f.paths.len() - 6);
        }
        let _ = writeln!(
            s,
            "          why: {}",
            wrap(&f.rationale, 66, "               ")
        );
    }
    let _ = writeln!(s, "\n MOST RECENT ACTIVITY\n {}", "-".repeat(76));
    for r in &sm.most_recent {
        let _ = writeln!(s, " {}  {}", r.timestamp.to_short(), r.path);
    }
    let _ = writeln!(s, "\n{}", INTERPRETATION);
    s
}

fn wrap(text: &str, width: usize, indent: &str) -> String {
    let mut out = String::new();
    let mut line = 0;
    for word in text.split_whitespace() {
        if line + word.len() + 1 > width && line > 0 {
            out.push('\n');
            out.push_str(indent);
            line = 0;
        } else if line > 0 {
            out.push(' ');
            line += 1;
        }
        out.push_str(word);
        line += word.len();
    }
    out
}
